//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevExpress.ProductsDemo.Win.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevExpress.ProductsDemo.Win.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;br&gt;&lt;br&gt;Address: &lt;b&gt;{0}&lt;/b&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddressHtml {
            get {
                return ResourceManager.GetString("AddressHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All files (*.*)|*.*과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Analytics {
            get {
                object obj = ResourceManager.GetObject("Analytics", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Announcements과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Announcements {
            get {
                return ResourceManager.GetString("Announcements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error: could not export appointments과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppointmentError {
            get {
                return ResourceManager.GetString("AppointmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowLeft {
            get {
                object obj = ResourceManager.GetObject("ArrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowRight {
            get {
                object obj = ResourceManager.GetObject("ArrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ASP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ASP {
            get {
                return ResourceManager.GetString("ASP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BandedReports {
            get {
                object obj = ResourceManager.GetObject("BandedReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;br&gt;Birth Date: &lt;b&gt;{0:d}&lt;/b&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BirthDateHtml {
            get {
                return ResourceManager.GetString("BirthDateHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BO_Task {
            get {
                object obj = ResourceManager.GetObject("BO_Task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap BO_Task_Large {
            get {
                object obj = ResourceManager.GetObject("BO_Task_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ByState_32x32 {
            get {
                object obj = ResourceManager.GetObject("ByState_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Calendar과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CalendarName {
            get {
                return ResourceManager.GetString("CalendarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Card_32x32 {
            get {
                object obj = ResourceManager.GetObject("Card_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Close_16x16 {
            get {
                object obj = ResourceManager.GetObject("Close_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Close_32x32 {
            get {
                object obj = ResourceManager.GetObject("Close_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Close the current search.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CloseSearchDescription {
            get {
                return ResourceManager.GetString("CloseSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Code_Central {
            get {
                object obj = ResourceManager.GetObject("Code_Central", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Collated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Collated {
            get {
                return ResourceManager.GetString("Collated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1,2,3   1,2,3  1,2,3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CollatedDescription {
            get {
                return ResourceManager.GetString("CollatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ColorMixer_32x32 {
            get {
                object obj = ResourceManager.GetObject("ColorMixer_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Completed_16x16 {
            get {
                object obj = ResourceManager.GetObject("Completed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Completed_32x32 {
            get {
                object obj = ResourceManager.GetObject("Completed_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Contact과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Contact_16x16 {
            get {
                object obj = ResourceManager.GetObject("Contact_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Contact_32x32 {
            get {
                object obj = ResourceManager.GetObject("Contact_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Contact_Us {
            get {
                object obj = ResourceManager.GetObject("Contact_Us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   List contacts in alphabetical order.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactAlphabeticalDescription {
            get {
                return ResourceManager.GetString("ContactAlphabeticalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group contacts by the states.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactByStateDescription {
            get {
                return ResourceManager.GetString("ContactByStateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display card presentation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactCardDescription {
            get {
                return ResourceManager.GetString("ContactCardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List contacts in the order of creation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactListDescription {
            get {
                return ResourceManager.GetString("ContactListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Contacts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactsName {
            get {
                return ResourceManager.GetString("ContactsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dr.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactTitleDr {
            get {
                return ResourceManager.GetString("ContactTitleDr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Miss과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactTitleMiss {
            get {
                return ResourceManager.GetString("ContactTitleMiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mr.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactTitleMr {
            get {
                return ResourceManager.GetString("ContactTitleMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mrs.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactTitleMrs {
            get {
                return ResourceManager.GetString("ContactTitleMrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ms.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactTitleMs {
            get {
                return ResourceManager.GetString("ContactTitleMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prof.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ContactTitleProf {
            get {
                return ResourceManager.GetString("ContactTitleProf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV files (*.csv)|*.csv과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CSVFilter {
            get {
                return ResourceManager.GetString("CSVFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Custom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Custom_Flag {
            get {
                object obj = ResourceManager.GetObject("Custom_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateDeleted {
            get {
                return ResourceManager.GetString("DateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Received과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateInbox {
            get {
                return ResourceManager.GetString("DateInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sent과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DateOutbox {
            get {
                return ResourceManager.GetString("DateOutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Deferred_32x32 {
            get {
                object obj = ResourceManager.GetObject("Deferred_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Delete_16x16 {
            get {
                object obj = ResourceManager.GetObject("Delete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("Delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Delete this contact.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteContactDescription {
            get {
                return ResourceManager.GetString("DeleteContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleted Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeletedItems {
            get {
                return ResourceManager.GetString("DeletedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this feed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteFeedDescription {
            get {
                return ResourceManager.GetString("DeleteFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteItemDescription {
            get {
                return ResourceManager.GetString("DeleteItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete this task.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteTaskDescription {
            get {
                return ResourceManager.GetString("DeleteTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Doctor {
            get {
                object obj = ResourceManager.GetObject("Doctor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Drafts과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Due Date can&apos;t be less than Start Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DueDateError {
            get {
                return ResourceManager.GetString("DueDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter Due Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DueDateWarning {
            get {
                return ResourceManager.GetString("DueDateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap EditContact_16x16 {
            get {
                object obj = ResourceManager.GetObject("EditContact_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap EditContact_32x32 {
            get {
                object obj = ResourceManager.GetObject("EditContact_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Edit this contact.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditContactDescription {
            get {
                return ResourceManager.GetString("EditContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit this feed&apos;s settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditFeedDescription {
            get {
                return ResourceManager.GetString("EditFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap EditTask_16x16 {
            get {
                object obj = ResourceManager.GetObject("EditTask_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap EditTask_32x32 {
            get {
                object obj = ResourceManager.GetObject("EditTask_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Edit this task.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EditTaskDescription {
            get {
                return ResourceManager.GetString("EditTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;br&gt;Email: &lt;b&gt;{0}&lt;/b&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EmailHtml {
            get {
                return ResourceManager.GetString("EmailHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred while exporting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ExportErrorText {
            get {
                return ResourceManager.GetString("ExportErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToCSV_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToCSV_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToHTML_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToHTML_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToImage_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToImage_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToMHT_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToMHT_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToPDF_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToPDF_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToRTF_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToRTF_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToText_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToText_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToXLS_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToXLS_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ExportToXLSX_32x32 {
            get {
                object obj = ResourceManager.GetObject("ExportToXLSX_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   BBC News과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedBBCNews {
            get {
                return ResourceManager.GetString("FeedBBCNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blogs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedBlogs {
            get {
                return ResourceManager.GetString("FeedBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Engadget과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedEngadget {
            get {
                return ResourceManager.GetString("FeedEngadget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please accept our apologies for the inconvenience. The feed URL is currently unavailable:&lt;br&gt;&lt;b&gt;{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedError {
            get {
                return ResourceManager.GetString("FeedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DevExpress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedGroupDX {
            get {
                return ResourceManager.GetString("FeedGroupDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Misc과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedGroupMisc {
            get {
                return ResourceManager.GetString("FeedGroupMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   News과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedNews {
            get {
                return ResourceManager.GetString("FeedNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;b&gt; &lt;/b&gt;Content is taken from the public &lt;color={1}&gt;{0}&lt;/color&gt; feed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedNote {
            get {
                return ResourceManager.GetString("FeedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Feeds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedsName {
            get {
                return ResourceManager.GetString("FeedsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stack Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedStackOverflow {
            get {
                return ResourceManager.GetString("FeedStackOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Videos과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedVideos {
            get {
                return ResourceManager.GetString("FeedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Webinars과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeedWebinars {
            get {
                return ResourceManager.GetString("FeedWebinars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Female과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag this item as a task with custom due date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlagCustomDescription {
            get {
                return ResourceManager.GetString("FlagCustomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag this item as a task for next week.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlagNextWeekDescription {
            get {
                return ResourceManager.GetString("FlagNextWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag this item as a task with no due date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlagNoDatekDescription {
            get {
                return ResourceManager.GetString("FlagNoDatekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag this item as a task to due at the end of the work week.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlagThisWeekDescription {
            get {
                return ResourceManager.GetString("FlagThisWeekDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag this item as a task with a due date of today.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlagTodayDescription {
            get {
                return ResourceManager.GetString("FlagTodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flag this item as a task with a due date of tomorrow.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlagTomorrowDescription {
            get {
                return ResourceManager.GetString("FlagTomorrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flip the layout of controls around a vertical axis.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FlipLayoutDescription {
            get {
                return ResourceManager.GetString("FlipLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward this item to someone else.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ForwardDescription {
            get {
                return ResourceManager.GetString("ForwardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   
        ///
        ///=================End of original message text===============과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ForwardTextEnd {
            get {
                return ResourceManager.GetString("ForwardTextEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is a forwarded message:
        ///
        ///=================Original message text===============
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ForwardTextStart {
            get {
                return ResourceManager.GetString("ForwardTextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Frameworks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frameworks {
            get {
                return ResourceManager.GetString("Frameworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To/From과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FromDeleted {
            get {
                return ResourceManager.GetString("FromDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FromInbox {
            get {
                return ResourceManager.GetString("FromInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FromOutbox {
            get {
                return ResourceManager.GetString("FromOutbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap GridContacts {
            get {
                object obj = ResourceManager.GetObject("GridContacts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap GridTasks {
            get {
                object obj = ResourceManager.GetObject("GridTasks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap High16x16 {
            get {
                object obj = ResourceManager.GetObject("High16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   High priority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML files (*.html)|*.html과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string HTMLFilter {
            get {
                return ResourceManager.GetString("HTMLFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IDE Tools과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IDETools {
            get {
                return ResourceManager.GetString("IDETools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BMP files (*.bmp)|*.bmp|Gif files (*.gif)|*.gif|Jpeg files (*.jpeg)|*.jpeg|PNG files (*.png)|*.png|Tiff files (*.tiff)|*.tiff|EMF files (*.emf)|.emf|WMF files (*.wmf)|*.wmf과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ImageFilter {
            get {
                return ResourceManager.GetString("ImageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Important_16x16 {
            get {
                object obj = ResourceManager.GetObject("Important_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Inbox과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ITEMS: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is earlier this month과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsEarlierThisMonth {
            get {
                return ResourceManager.GetString("IsEarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is earlier this week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsEarlierThisWeek {
            get {
                return ResourceManager.GetString("IsEarlierThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is earlier this year과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsEarlierThisYear {
            get {
                return ResourceManager.GetString("IsEarlierThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is last week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsLastWeek {
            get {
                return ResourceManager.GetString("IsLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is Today과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsToday {
            get {
                return ResourceManager.GetString("IsToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Is yesterday과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsYesterday {
            get {
                return ResourceManager.GetString("IsYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Landscape Orientation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LandscapeOrientation {
            get {
                return ResourceManager.GetString("LandscapeOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap LayoutFlip_16x16 {
            get {
                object obj = ResourceManager.GetObject("LayoutFlip_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap LayoutFlip_32x32 {
            get {
                object obj = ResourceManager.GetObject("LayoutFlip_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap List_32x32 {
            get {
                object obj = ResourceManager.GetObject("List_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ListByDate_32x32 {
            get {
                object obj = ResourceManager.GetObject("ListByDate_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Low16x16 {
            get {
                object obj = ResourceManager.GetObject("Low16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Low priority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MailName {
            get {
                return ResourceManager.GetString("MailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Male과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Moderate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsModerate {
            get {
                return ResourceManager.GetString("MarginsModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top:	25 mm	Bottom:	25 mm
        ///Left:	19 mm	Right:	19 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsModerateDescription {
            get {
                return ResourceManager.GetString("MarginsModerateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Narrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsNarrow {
            get {
                return ResourceManager.GetString("MarginsNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top:	12 mm	Bottom:	12 mm
        ///Left:	12 mm	Right:	12 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsNarrowDescription {
            get {
                return ResourceManager.GetString("MarginsNarrowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsNormal {
            get {
                return ResourceManager.GetString("MarginsNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top:	25 mm	Bottom:	25 mm
        ///Left:	25 mm	Right:	25 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsNormalDescription {
            get {
                return ResourceManager.GetString("MarginsNormalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wide과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsWide {
            get {
                return ResourceManager.GetString("MarginsWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top:	25 mm	Bottom:	25 mm
        ///Left:	50 mm	Right:	50 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MarginsWideDescription {
            get {
                return ResourceManager.GetString("MarginsWideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium priority과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MediumPriority {
            get {
                return ResourceManager.GetString("MediumPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap MemoStyle {
            get {
                object obj = ResourceManager.GetObject("MemoStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Memo Style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MemoStyleString {
            get {
                return ResourceManager.GetString("MemoStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Messages과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MHT files (*.mht)|*.mht과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MHTFilter {
            get {
                return ResourceManager.GetString("MHTFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Miss {
            get {
                object obj = ResourceManager.GetObject("Miss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Mr {
            get {
                object obj = ResourceManager.GetObject("Mr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Mrs {
            get {
                object obj = ResourceManager.GetObject("Mrs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Ms {
            get {
                object obj = ResourceManager.GetObject("Ms", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap MultiplePagesLarge {
            get {
                object obj = ResourceManager.GetObject("MultiplePagesLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NavigationBar_16x16 {
            get {
                object obj = ResourceManager.GetObject("NavigationBar_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NavigationBar_32x32 {
            get {
                object obj = ResourceManager.GetObject("NavigationBar_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Switch between modules.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NavigationDescription {
            get {
                return ResourceManager.GetString("NavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NewContact_16x16 {
            get {
                object obj = ResourceManager.GetObject("NewContact_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NewContact_32x32 {
            get {
                object obj = ResourceManager.GetObject("NewContact_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Create a new contact.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewContactDescription {
            get {
                return ResourceManager.GetString("NewContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new feed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewFeedDescription {
            get {
                return ResourceManager.GetString("NewFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewFirstName {
            get {
                return ResourceManager.GetString("NewFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create a new mail.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewItemDescription {
            get {
                return ResourceManager.GetString("NewItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewLastName {
            get {
                return ResourceManager.GetString("NewLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NewTask_16x16 {
            get {
                object obj = ResourceManager.GetObject("NewTask_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NewTask_32x32 {
            get {
                object obj = ResourceManager.GetObject("NewTask_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Create a new task.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewTaskDescription {
            get {
                return ResourceManager.GetString("NewTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New task과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NewTaskName {
            get {
                return ResourceManager.GetString("NewTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Next Week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NextWeek_Flag {
            get {
                object obj = ResourceManager.GetObject("NextWeek_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   No Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoDate {
            get {
                return ResourceManager.GetString("NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap NoDate_Flag {
            get {
                object obj = ResourceManager.GetObject("NoDate_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   None과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print One Sided과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OneSide {
            get {
                return ResourceManager.GetString("OneSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only print on one side of the page과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OneSideDescription {
            get {
                return ResourceManager.GetString("OneSideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Online_Help {
            get {
                object obj = ResourceManager.GetObject("Online_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Do you want to open this file?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OpentFileQuestion {
            get {
                return ResourceManager.GetString("OpentFileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Overdue_32x32 {
            get {
                object obj = ResourceManager.GetObject("Overdue_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Owner {
            get {
                object obj = ResourceManager.GetObject("Owner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Mr.Brooks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page {0} of 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsModerate {
            get {
                object obj = ResourceManager.GetObject("PageMarginsModerate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsNarrow {
            get {
                object obj = ResourceManager.GetObject("PageMarginsNarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsNormal {
            get {
                object obj = ResourceManager.GetObject("PageMarginsNormal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PageMarginsWide {
            get {
                object obj = ResourceManager.GetObject("PageMarginsWide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PageOrientationLandscape {
            get {
                object obj = ResourceManager.GetObject("PageOrientationLandscape", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PageOrientationPortrait {
            get {
                object obj = ResourceManager.GetObject("PageOrientationPortrait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A3 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A4 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A5 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_A6 {
            get {
                object obj = ResourceManager.GetObject("PaperKind_A6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Executive {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Executive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Legal {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Legal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Letter {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Letter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PaperKind_Tabloid {
            get {
                object obj = ResourceManager.GetObject("PaperKind_Tabloid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   A3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA3 {
            get {
                return ResourceManager.GetString("PaperKindA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   296 mm x 420 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA3Description {
            get {
                return ResourceManager.GetString("PaperKindA3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A4과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA4 {
            get {
                return ResourceManager.GetString("PaperKindA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   210 mm x 296 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA4Description {
            get {
                return ResourceManager.GetString("PaperKindA4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A5과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA5 {
            get {
                return ResourceManager.GetString("PaperKindA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   148 mm x 210 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA5Description {
            get {
                return ResourceManager.GetString("PaperKindA5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A6과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA6 {
            get {
                return ResourceManager.GetString("PaperKindA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   105 mm x 148 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindA6Description {
            get {
                return ResourceManager.GetString("PaperKindA6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindExecutive {
            get {
                return ResourceManager.GetString("PaperKindExecutive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   184 mm x 266 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindExecutiveDescription {
            get {
                return ResourceManager.GetString("PaperKindExecutiveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Legal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindLegal {
            get {
                return ResourceManager.GetString("PaperKindLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   215 mm x 355 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindLegalDescription {
            get {
                return ResourceManager.GetString("PaperKindLegalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Letter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindLetter {
            get {
                return ResourceManager.GetString("PaperKindLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   215 mm x 279 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindLetterDescription {
            get {
                return ResourceManager.GetString("PaperKindLetterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tabloid과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindTabloid {
            get {
                return ResourceManager.GetString("PaperKindTabloid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   279 mm x 431 mm과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PaperKindTabloidDescription {
            get {
                return ResourceManager.GetString("PaperKindTabloidDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF files (*.pdf)|*.pdf과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PDFFilter {
            get {
                return ResourceManager.GetString("PDFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PDFViewer {
            get {
                object obj = ResourceManager.GetObject("PDFViewer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Personal과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;br&gt;Phone: &lt;b&gt;{0}&lt;/b&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PhoneHtml {
            get {
                return ResourceManager.GetString("PhoneHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit Image과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Picture100Zoom {
            get {
                return ResourceManager.GetString("Picture100Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Pivot {
            get {
                object obj = ResourceManager.GetObject("Pivot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Portrait Orientation과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PortraitOrientation {
            get {
                return ResourceManager.GetString("PortraitOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap PrintDirectLarge {
            get {
                object obj = ResourceManager.GetObject("PrintDirectLarge", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Prioritized_32x32 {
            get {
                object obj = ResourceManager.GetObject("Prioritized_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Priority_16x16 {
            get {
                object obj = ResourceManager.GetObject("Priority_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Set priority for this item.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PriorityDescription {
            get {
                return ResourceManager.GetString("PriorityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   High과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Low과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Medium과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Professor {
            get {
                object obj = ResourceManager.GetObject("Professor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Please Wait과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgressPanelCaption {
            get {
                return ResourceManager.GetString("ProgressPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgressPanelDescription {
            get {
                return ResourceManager.GetString("ProgressPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap reading {
            get {
                object obj = ResourceManager.GetObject("reading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_16x16 {
            get {
                object obj = ResourceManager.GetObject("Refresh_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Refresh_32x32 {
            get {
                object obj = ResourceManager.GetObject("Refresh_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Reload this feed from the server.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RefreshFeedDescription {
            get {
                return ResourceManager.GetString("RefreshFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap reminder {
            get {
                object obj = ResourceManager.GetObject("reminder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   REMINDERS: {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReminderText {
            get {
                return ResourceManager.GetString("ReminderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply to the sender and all other recipients of this message.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReplyAllDescription {
            get {
                return ResourceManager.GetString("ReplyAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reply to the sender of this message.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReplyDescription {
            get {
                return ResourceManager.GetString("ReplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dear, {0}
        ///
        ///{1}, you wrote:
        ///
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReplyText {
            get {
                return ResourceManager.GetString("ReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotate the layout of controls.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RotateLayoutDescription {
            get {
                return ResourceManager.GetString("RotateLayoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RTF files (*.rtf)|*.rtf과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RTFFilter {
            get {
                return ResourceManager.GetString("RTFFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This value cannot be empty과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RuleIsNotBlankWarning {
            get {
                return ResourceManager.GetString("RuleIsNotBlankWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This value must be unique and does not equal empty.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RuleUniqueNamesWarning {
            get {
                return ResourceManager.GetString("RuleUniqueNamesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Save_16x16 {
            get {
                object obj = ResourceManager.GetObject("Save_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Save_32x32 {
            get {
                object obj = ResourceManager.GetObject("Save_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAll_32x32 {
            get {
                object obj = ResourceManager.GetObject("SaveAll_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Do you want to save changes?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SaveQuestion {
            get {
                return ResourceManager.GetString("SaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Scheduler {
            get {
                object obj = ResourceManager.GetObject("Scheduler", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Clear the applied filter.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchClearDescription {
            get {
                return ResourceManager.GetString("SearchClearDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close the Search tab.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchCloseDescription {
            get {
                return ResourceManager.GetString("SearchCloseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select columns against which a search is performed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchColumnsDescription {
            get {
                return ResourceManager.GetString("SearchColumnsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display e-mail messages that have attachments.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchHasAttachmentDescription {
            get {
                return ResourceManager.GetString("SearchHasAttachmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display prioritized e-mail messages.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchImportantDescription {
            get {
                return ResourceManager.GetString("SearchImportantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter e-mail messages by date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchReceivedDescription {
            get {
                return ResourceManager.GetString("SearchReceivedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset to the default filter column list.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchResetDescription {
            get {
                return ResourceManager.GetString("SearchResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search {0} (Ctrl + E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchString {
            get {
                return ResourceManager.GetString("SearchString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display unread e-mail messages.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SearchUnreadDescription {
            get {
                return ResourceManager.GetString("SearchUnreadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sent Items과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SentItems {
            get {
                return ResourceManager.GetString("SentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display message previews과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ShowPreviewDescription {
            get {
                return ResourceManager.GetString("ShowPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap SortAsc_32x32 {
            get {
                object obj = ResourceManager.GetObject("SortAsc_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Spreadsheet {
            get {
                object obj = ResourceManager.GetObject("Spreadsheet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Starting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap TableStyle {
            get {
                object obj = ResourceManager.GetObject("TableStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Table Style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TableStyleString {
            get {
                return ResourceManager.GetString("TableStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   House Chores과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskCategoryHouseChores {
            get {
                return ResourceManager.GetString("TaskCategoryHouseChores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskCategoryOffice {
            get {
                return ResourceManager.GetString("TaskCategoryOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shopping과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskCategoryShopping {
            get {
                return ResourceManager.GetString("TaskCategoryShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List completed tasks and group them by date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskCompletedDescription {
            get {
                return ResourceManager.GetString("TaskCompletedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List deferred tasks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskDeferredDescription {
            get {
                return ResourceManager.GetString("TaskDeferredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List all tasks and group them by date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskListDescription {
            get {
                return ResourceManager.GetString("TaskListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List overdue tasks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskOverdueDescription {
            get {
                return ResourceManager.GetString("TaskOverdueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group tasks by priority.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskPrioritizedDescription {
            get {
                return ResourceManager.GetString("TaskPrioritizedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List all tasks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskSimpleListDescription {
            get {
                return ResourceManager.GetString("TaskSimpleListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tasks과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TasksName {
            get {
                return ResourceManager.GetString("TasksName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskStatusCompleted {
            get {
                return ResourceManager.GetString("TaskStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deferred과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskStatusDeferred {
            get {
                return ResourceManager.GetString("TaskStatusDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In Progress과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskStatusInProgress {
            get {
                return ResourceManager.GetString("TaskStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not Started과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskStatusNotStarted {
            get {
                return ResourceManager.GetString("TaskStatusNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting On Someone Else과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskStatusWaitingOnSomeoneElse {
            get {
                return ResourceManager.GetString("TaskStatusWaitingOnSomeoneElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List Today&apos;s tasks.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskTodayDescription {
            get {
                return ResourceManager.GetString("TaskTodayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List non-completed tasks and group them by date.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TaskToDoListDescription {
            get {
                return ResourceManager.GetString("TaskToDoListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MyFeed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TempFeedName {
            get {
                return ResourceManager.GetString("TempFeedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MyGroup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TempGroupName {
            get {
                return ResourceManager.GetString("TempGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text files (*.txt)|*.txt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TextFilter {
            get {
                return ResourceManager.GetString("TextFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Week과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ThisWeek_Flag {
            get {
                object obj = ResourceManager.GetObject("ThisWeek_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Today과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Today_16x16 {
            get {
                object obj = ResourceManager.GetObject("Today_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Today_32x32 {
            get {
                object obj = ResourceManager.GetObject("Today_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Today_Flag {
            get {
                object obj = ResourceManager.GetObject("Today_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap ToDoList_32x32 {
            get {
                object obj = ResourceManager.GetObject("ToDoList_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Tomorrow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Tomorrow_Flag {
            get {
                object obj = ResourceManager.GetObject("Tomorrow_Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Manually Print on Both Sides과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TwoSide {
            get {
                return ResourceManager.GetString("TwoSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload paper when prompted to print the second side과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TwoSideDescription {
            get {
                return ResourceManager.GetString("TwoSideDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uncollated과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uncollated {
            get {
                return ResourceManager.GetString("Uncollated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1,1,1  2,2,2  3,3,3과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UncollatedDescription {
            get {
                return ResourceManager.GetString("UncollatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Unknown_user {
            get {
                object obj = ResourceManager.GetObject("Unknown_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   If this item is marked as unread mark it as read.
        ///If this item is marked as read mark it as though you haven&apos;t read it yet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnreadReadDescription {
            get {
                return ResourceManager.GetString("UnreadReadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap WeatherMap {
            get {
                object obj = ResourceManager.GetObject("WeatherMap", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   WinForms과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WinForms {
            get {
                return ResourceManager.GetString("WinForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap WordProcessing {
            get {
                object obj = ResourceManager.GetObject("WordProcessing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Work과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Work {
            get {
                return ResourceManager.GetString("Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap WYSIWYGReports {
            get {
                object obj = ResourceManager.GetObject("WYSIWYGReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   XLS files (*.xls)|*.xls과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XLSFilter {
            get {
                return ResourceManager.GetString("XLSFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   XLSX files (*.xls)|*.xls과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string XLSXFilter {
            get {
                return ResourceManager.GetString("XLSXFilter", resourceCulture);
            }
        }
    }
}
